'use client';

import React from 'react';
import { ProtectedRoute } from '@/components/ProtectedRoute';
import { Layout } from '@/components/Layout';
import { ActionButton, Pill, SectionTitle, SurfaceCard } from '@/components/student/DesignSystem';
import { RecommendationCard, RecommendationItem } from '@/components/RecommendationCard';
import { studentApi } from '@/lib/api';

const filterOptions = {
    type: ['All', 'Course', 'Certification', 'Book', 'Project', 'CareerPath'],
    priority: ['All', 'High', 'Medium', 'Low'],
    status: ['All', 'Active', 'Completed', 'Ignored'],
};

const emptyState = {
    title: 'Aucune recommandation pour le moment',
    description: "Definissez un objectif de carriere pour activer les suggestions personnalisees.",
};

export default function RecommendationsPage() {
    const [loading, setLoading] = React.useState(true);
    const [refreshing, setRefreshing] = React.useState(false);
    const [notice, setNotice] = React.useState<string | null>(null);
    const [recommendations, setRecommendations] = React.useState<RecommendationItem[]>([]);
    const [filters, setFilters] = React.useState({ type: 'All', priority: 'All', status: 'Active' });
    const [autoGenerated, setAutoGenerated] = React.useState(false);

    const fetchRecommendations = React.useCallback(async () => {
        try {
            const params: Record<string, string | number> = { limit: 60, sort: 'priority' };
            if (filters.type !== 'All') params.type = filters.type;
            if (filters.priority !== 'All') params.priority = filters.priority;
            if (filters.status !== 'All') params.status = filters.status;

            const response = await studentApi.getRecommendations(params);
            setRecommendations(response.data?.data?.recommendations || []);
        } catch (error) {
            setRecommendations([]);
        } finally {
            setLoading(false);
        }
    }, [filters]);

    React.useEffect(() => {
        fetchRecommendations();
    }, [fetchRecommendations]);

    const handleGenerate = async (silent?: boolean) => {
        setRefreshing(true);
        try {
            const response = await studentApi.generateRecommendations();
            const created = Number(response.data?.data?.created || 0);
            if (created > 0) {
                setNotice('Nouvelles recommandations disponibles.');
            } else if (!silent) {
                setNotice('Vos recommandations sont a jour.');
            }
            await fetchRecommendations();
        } finally {
            setRefreshing(false);
        }
    };

    React.useEffect(() => {
        if (!loading && recommendations.length === 0 && !autoGenerated) {
            setAutoGenerated(true);
            handleGenerate(true);
        }
    }, [loading, recommendations.length, autoGenerated]);

    const handleStart = async (item: RecommendationItem) => {
        try {
            if (item.link) {
                window.open(item.link, '_blank', 'noopener,noreferrer');
            }
            await studentApi.startRecommendation(item._id);
            await fetchRecommendations();
        } catch (error) {
            // Keep UI stable on API error.
        }
    };

    const handleComplete = async (item: RecommendationItem) => {
        try {
            await studentApi.completeRecommendation(item._id);
            await fetchRecommendations();
        } catch (error) {
            // Keep UI stable on API error.
        }
    };

    const handleIgnore = async (item: RecommendationItem) => {
        try {
            await studentApi.ignoreRecommendation(item._id);
            await fetchRecommendations();
        } catch (error) {
            // Keep UI stable on API error.
        }
    };

    return (
        <ProtectedRoute requiredRole="STUDENT">
            <Layout>
                <div className="max-w-[1600px] mx-auto space-y-6">
                    <SectionTitle
                        title="Recommandations IA"
                        subtitle="Cartes personnalisees basees sur vos competences et vos objectifs"
                        actions={
                            <>
                                <Pill className="bg-[#1d4ed8] text-white">IA Active</Pill>
                                <ActionButton icon={<span>↻</span>} onClick={() => handleGenerate()} disabled={refreshing}>
                                    {refreshing ? 'Actualisation...' : 'Actualiser'}
                                </ActionButton>
                            </>
                        }
                    />

                    {notice ? (
                        <SurfaceCard className="p-4 flex items-center justify-between">
                            <p className="text-sm text-[#1d4ed8] font-semibold">{notice}</p>
                            <ActionButton onClick={() => setNotice(null)}>Fermer</ActionButton>
                        </SurfaceCard>
                    ) : null}

                    <SurfaceCard className="p-4">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            {(['type', 'priority', 'status'] as const).map((key) => (
                                <label key={key} className="text-sm font-semibold text-[#4b5563]">
                                    {key === 'type' ? 'Type' : key === 'priority' ? 'Priorite' : 'Statut'}
                                    <select
                                        className="mt-2 w-full rounded-xl border border-[#d7dbe4] bg-white px-3 py-2 text-sm"
                                        value={filters[key]}
                                        onChange={(event) => setFilters((prev) => ({ ...prev, [key]: event.target.value }))}
                                    >
                                        {filterOptions[key].map((option) => (
                                            <option key={option} value={option}>
                                                {option === 'All' ? 'Tous' : option}
                                            </option>
                                        ))}
                                    </select>
                                </label>
                            ))}
                        </div>
                    </SurfaceCard>

                    {loading ? (
                        <SurfaceCard className="p-6">
                            <p className="text-[#4b5563] text-lg">Chargement des recommandations...</p>
                        </SurfaceCard>
                    ) : recommendations.length === 0 ? (
                        <SurfaceCard className="p-6 text-center">
                            <p className="text-lg font-semibold text-black">{emptyState.title}</p>
                            <p className="mt-2 text-sm text-[#6b7280]">{emptyState.description}</p>
                        </SurfaceCard>
                    ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
                            {recommendations.map((item) => (
                                <RecommendationCard
                                    key={item._id}
                                    item={item}
                                    onStart={handleStart}
                                    onComplete={handleComplete}
                                    onIgnore={handleIgnore}
                                    disabled={refreshing}
                                />
                            ))}
                        </div>
                    )}
                </div>
            </Layout>
        </ProtectedRoute>
    );
}
